console.log("Hello World ");
let a = "xyz";
console.log(a);
let b = 123;
console.log(b);
let c = true;
console.log(c);
let myName = "sohail";
let age = 19;
let isStudent = true;
console.log(`My name is ${myName} and my age is : ${age} `);
